### ISSUE TITLE
Does not work with 2021 edition

### ISSUE THREAD

**Issue by weezy20** [Endle/rust-bundler-cp#34]
I get ```stderr: error[E0670]: `async fn` is not permitted in Rust 2015```

**Comment by Endle** [comment]
Thank you for reporting it. Can you add a few more details so I can reproduce it?

**Comment by weezy20** [comment]
I installed this and tried it on this repo : https://github.com/r0gue-io/pop-cli.

**Comment by Endle** [comment]
The reason is that rust-bundler-cp doesn't support cargo dependencies. I've updated readme

**Comment by weezy20** [comment]
@Endle Any reason why?

**Comment by Endle** [comment]
rust-bundler-cp will not recursively load [dependencies] in Cargo.toml. 


Can you share your use case for it?

**Comment by weezy20** [comment]
I don't have a particular use case, just curious about what's possible. Since cargo dependencies are just extern crates, I could imagine a scenario where it would be possible but at the same time I also think that there are unseen challenges. I have been looking into various bundlers so that I could compile a single `.rs` file with all libraries linked to it, but yeah, it would be a lot of code duplication from `cargo` which is not trivial by any means.
